import {useEffect,useState} from 'react';
import {listAsesores} from '../../services/asesoresApi.js';
import {getHistory,columns} from '../../services/tiemposApi.js';
import TiemposTable from './TiemposTable.jsx';
export default function AsesorHistory({version,onEdit}){
 const [search,setSearch]=useState(''),[advisors,setAdvisors]=useState([]),[filters,setFilters]=useState({asesorId:'',tipo:'mes',fecha:new Date().toLocaleDateString('en-CA'),desde:'',hasta:''}),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>listAsesores({search,limit:100},c.signal).then(r=>setAdvisors(r.data)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}),250);return()=>{clearTimeout(timer);c.abort();};},[search]);
 useEffect(()=>{setData(null);if(!filters.asesorId||(filters.tipo==='rango'&&(!filters.desde||!filters.hasta))||(!filters.fecha&&filters.tipo!=='rango'))return;const c=new AbortController();setError('');setLoading(true);getHistory({...filters,page,limit:25},c.signal).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[filters,page,version]);
 function filter(k,v){setFilters({...filters,[k]:v});setPage(1);}
 return <><div className="list-heading"><div><p className="section-kicker">HISTORIAL POR PERSONA</p><h2>Acumulados por asesor</h2></div></div><div className="time-filters"><label>Buscar asesor<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre o campaña"/></label><label>Asesor<select value={filters.asesorId} onChange={e=>filter('asesorId',e.target.value)}><option value="">Selecciona un asesor</option>{advisors.map(a=><option value={a._id} key={a._id}>{a.nombreAsesor} · {a.campana}</option>)}</select><small>Hasta 100 coincidencias; afina la búsqueda.</small></label><label>Periodo<select value={filters.tipo} onChange={e=>filter('tipo',e.target.value)}>{[['dia','Día'],['semana','Semana'],['mes','Mes'],['ano','Año'],['rango','Rango personalizado']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{filters.tipo==='rango'?<><label>Desde<input type="date" value={filters.desde} onChange={e=>filter('desde',e.target.value)}/></label><label>Hasta<input type="date" value={filters.hasta} onChange={e=>filter('hasta',e.target.value)}/></label></>:<label>Fecha de referencia<input type="date" value={filters.fecha} onChange={e=>filter('fecha',e.target.value)}/></label>}</div>{error&&<div className="notice error" role="alert">{error}</div>}{loading?<p role="status" className="list-placeholder">Consultando historial…</p>:!data?<p className="list-placeholder">Selecciona un asesor y un periodo para consultar sus tiempos.</p>:<><p className="muted">{data.data.periodo.desde} al {data.data.periodo.hasta} · {data.data.dias} días con registro · {data.pagination.total} filas diarias. Los valores sin dato se excluyen de la suma.</p><div className="time-summary">{columns.filter(([k])=>data.data.acumulados[k]).map(([k,label])=><div key={k}><span>{label}</span><strong>{data.pagination.total>0&&data.data.acumulados[k].diasPendientes===data.pagination.total?'Sin dato':data.data.acumulados[k].formato}</strong><small>{data.data.acumulados[k].diasPendientes?`${data.data.acumulados[k].diasPendientes} días sin dato · suma parcial`:'Suma de valores conocidos'}</small></div>)}</div>{data.data.detalle.length?<TiemposTable rows={data.data.detalle} historical onEdit={onEdit}/>:<p className="list-placeholder">No hay registros en este periodo.</p>}<div className="pagination"><span>Página {page} de {data.pagination.pages}</span><div><button className="button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button className="button secondary" disabled={page>=data.pagination.pages} onClick={()=>setPage(page+1)}>Siguiente</button></div></div></>}</>;
}
