import {useState} from 'react';
import Modal from '../asesores/Modal.jsx';
import {uploadTimes,deleteImport,editTime,columns,duration} from '../../services/tiemposApi.js';
export function UploadModal({item,onClose,onSaved}){
 const [file,setFile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();if(!file)return;setBusy(true);setError('');try{const r=await uploadTimes(file,item?._id);onSaved(r.data);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title={item?'Reemplazar archivo':'Importar tiempos'} onClose={onClose} busy={busy}><form onSubmit={submit}><p className="muted">{item?`Se sustituirá ${item.nombreArchivoOriginal}, del ${item.fechaDatos}. El nuevo archivo debe tener la misma fecha. Las correcciones manuales se sustituirán por el nuevo procesamiento.`:'Selecciona el reporte diario. Se guardará el original y se relacionarán sus filas con los asesores registrados.'}</p><label className="file-picker">Archivo CSV, XLSX o XLS · máximo 5 MB<input type="file" accept=".csv,.xlsx,.xls" required disabled={busy} onChange={e=>{setError('');const f=e.target.files[0];if(f?.size>5*1024*1024){setFile(null);setError('El archivo supera 5 MB.');}else setFile(f);}}/></label><p className="muted small">Las columnas pueden cambiar de orden; los encabezados deben corresponder al reporte de tiempos. Las filas no identificadas se marcan sin crear asesores.</p>{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button" disabled={!file||busy}>{busy?'Procesando…':item?'Confirmar reemplazo':'Importar archivo'}</button></div></form></Modal>;
}
export function DeleteModal({item,onClose,onSaved}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 async function remove(){setBusy(true);setError('');try{await deleteImport(item._id);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title="Eliminar importación" onClose={onClose} busy={busy}><p>Se eliminarán <strong>{item.nombreArchivoOriginal}</strong>, su reporte del {item.fechaDatos} y el archivo original almacenado.</p><p className="muted">Los asesores se conservarán. Esta acción no se puede deshacer y los acumulados cambiarán.</p><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo que quiero eliminar esta importación.</label>{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button danger" disabled={busy||!confirmed} onClick={remove}>{busy?'Eliminando…':'Eliminar definitivamente'}</button></div></Modal>;
}
export function EditModal({record,onClose,onSaved}){
 const editable=columns.filter(([k])=>!['nombreAsesor','totalAdeudo'].includes(k));
 const [values,setValues]=useState(Object.fromEntries(editable.map(([k])=>[k,record[k]===null||record[k]===undefined?'':k.endsWith('Jornada')?record[k]:duration(record[k])]))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const changed=Object.fromEntries(Object.entries(values).filter(([k,v])=>v!==(record[k]===null||record[k]===undefined?'':k.endsWith('Jornada')?record[k]:duration(record[k]))).map(([k,v])=>[k,v||null]));if(!Object.keys(changed).length){setError('Modifica al menos un campo.');return;}await editTime(record._id,changed);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title="Editar registro" onClose={onClose} busy={busy}><p><strong>{record.nombreAsesor}</strong> · {record.fecha}</p><form className="asesor-form" onSubmit={submit}><div className="mapping-grid">{editable.map(([k,label])=><label key={k}>{label}<input value={values[k]} placeholder="HH:mm:ss" pattern={k.endsWith('Jornada')?'([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]':'[0-9]{1,3}:[0-5][0-9]:[0-5][0-9]'} onChange={e=>setValues({...values,[k]:e.target.value})}/></label>)}</div><p className="muted">Vacío significa sin dato. Se conservará el valor anterior para auditoría. El total se recalcula como adeudo de jornada + break + baño; no es editable directamente.</p>{record.modificadoManualmente&&<p className="muted small">Última corrección: {new Date(record.fechaModificacionManual).toLocaleString('es-MX')}</p>}{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button" disabled={busy}>{busy?'Guardando…':'Guardar corrección'}</button></div></form></Modal>;
}
