import {useEffect,useState} from 'react';
import Hero from '../components/Hero.jsx';
import TiemposTable from '../components/tiempos/TiemposTable.jsx';
import AsesorHistory from '../components/tiempos/AsesorHistory.jsx';
import {UploadModal,DeleteModal,EditModal} from '../components/tiempos/TiemposModals.jsx';
import {listImports,getReport,downloadTimes,displayDate} from '../services/tiemposApi.js';
import '../styles/tiempos.css';
export default function TiemposPage(){
 const [tab,setTab]=useState('archivos'),[filters,setFilters]=useState({fecha:'',nombre:''}),[page,setPage]=useState(1),[version,setVersion]=useState(0),[data,setData]=useState({data:[],pagination:{total:0,pages:1}}),[reportId,setReportId]=useState(null),[report,setReport]=useState(null),[reportPage,setReportPage]=useState(1),[loading,setLoading]=useState(true),[reportLoading,setReportLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[downloading,setDownloading]=useState(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);const timer=setTimeout(()=>listImports({...filters,page,limit:15},c.signal).then(r=>{if(c.signal.aborted)return;if(page>r.pagination.pages){setPage(r.pagination.pages);return;}setData(r);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);}),200);return()=>{clearTimeout(timer);c.abort();};},[filters,page,version]);
 useEffect(()=>{if(!reportId){setReport(null);return;}const c=new AbortController();setReportLoading(true);setReport(null);getReport(reportId,c.signal).then(r=>{if(!c.signal.aborted)setReport(r.data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setReportLoading(false);});return()=>c.abort();},[reportId,version]);
 function refresh(message){setModal(null);setError('');setNotice(message);setVersion(v=>v+1);}
 async function download(item,original){setDownloading(true);setError('');try{await downloadTimes(item,original);setNotice('Archivo descargado.');}catch(e){setError(e.message);}finally{setDownloading(false);}}
 function view(item){setError('');setReportId(item._id);setReportPage(1);setTab('reporte');}
 const selected=report?.importacion;
 return <div className="asesores-page tiempos-page"><Hero title="TIEMPOS" subtitle="Cada jornada, en su lugar. Consulta archivos, reportes y acumulados." eyebrow="EL HISTORIAL DE TU EQUIPO"><div className="hero-actions"><button className="button white" onClick={()=>setModal({type:'upload'})}>↑ Importar archivo</button><button className="light-button" onClick={()=>setTab('archivos')}>Historial de archivos</button><button className="light-button" onClick={()=>setTab('asesor')}>Consultar asesor</button></div></Hero><section className="asesores-content"><div className="time-tabs" aria-label="Vistas de tiempos">{[['archivos','Archivos importados'],['reporte','Reporte diario'],['asesor','Historial por asesor']].map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>{notice&&<div className="notice success" role="status">{notice}<button aria-label="Cerrar mensaje" onClick={()=>setNotice('')}>×</button></div>}{error&&<div className="notice error" role="alert">{error}<button onClick={()=>{setError('');setVersion(v=>v+1);}}>Reintentar</button></div>}
 {tab==='archivos'&&<><div className="list-heading"><div><p className="section-kicker">ARCHIVOS QUE CONSTRUYEN TU HISTORIAL</p><h2>Historial de importaciones</h2></div><span className="count-label">{data.pagination.total} archivos</span></div><div className="time-filters"><label>Nombre del archivo<input value={filters.nombre} maxLength={80} placeholder="Buscar archivo…" onChange={e=>{setFilters({...filters,nombre:e.target.value});setPage(1);}}/></label><label>Fecha de los datos<input type="date" value={filters.fecha} onChange={e=>{setFilters({...filters,fecha:e.target.value});setPage(1);}}/></label><button className="button secondary" onClick={()=>{setFilters({fecha:'',nombre:''});setPage(1);}}>Limpiar filtros</button></div>{loading?<p className="list-placeholder" role="status">Cargando archivos…</p>:data.data.length?<div className="table-scroll" tabIndex="0" role="region" aria-label="Archivos importados"><table className="asesor-table import-table card-table"><thead><tr><th>Archivo / fecha de carga</th><th>Fecha de datos</th><th>Procesados</th><th>Incidencias</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.data.map(item=><tr key={item._id}><td className="name-cell" data-label="Archivo">{item.nombreArchivoOriginal}<small>{new Date(item.createdAt).toLocaleString('es-MX')} · {(item.tamanoArchivo/1024).toFixed(1)} KB</small></td><td data-label="Fecha de datos">{displayDate(item.fechaDatos)}</td><td data-label="Procesados">{item.registrosProcesados} / {item.registrosEncontrados}</td><td data-label="Incidencias">{item.registrosConError} errores · {item.asesoresNoIdentificados} sin identificar</td><td data-label="Estado">{item.estado}</td><td data-label="Acciones"><div className="file-actions"><button onClick={()=>view(item)}>Ver</button><button disabled={downloading} onClick={()=>download(item,true)}>Descargar original</button><button disabled={downloading} onClick={()=>download(item,false)}>Descargar reporte</button><button onClick={()=>setModal({type:'upload',item})}>Reemplazar</button><button className="delete-link" onClick={()=>setModal({type:'delete',item})}>Eliminar</button></div></td></tr>)}</tbody></table></div>:<div className="list-placeholder"><h3>Sin archivos para mostrar</h3><p>Importa un archivo diario o cambia los filtros.</p></div>}<div className="pagination"><span>Página {page} de {data.pagination.pages} · 15 por página</span><div><button className="button secondary" disabled={loading||page===1} onClick={()=>setPage(page-1)}>Anterior</button><button className="button secondary" disabled={loading||page>=data.pagination.pages} onClick={()=>setPage(page+1)}>Siguiente</button></div></div></>}
 {tab==='reporte'&&(reportLoading?<p className="list-placeholder" role="status">Cargando reporte…</p>:!report?<p className="list-placeholder">Elige «Ver» en un archivo del historial para abrir su reporte.</p>:<><div className="list-heading"><div><p className="section-kicker">REPORTE DIARIO</p><h2>{displayDate(selected.fechaDatos)}</h2><p className="muted">{selected.nombreArchivoOriginal}</p></div><button className="button secondary" disabled={downloading} onClick={()=>download(selected,false)}>↓ Descargar reporte</button></div><div className="notice">Total en adeudo = adeudo de jornada + break + baño. Pausa y retro muestran el consumo registrado. El break permitido proviene del asesor y baño permite 15 minutos. «Sin dato» indica información faltante.</div><div className="import-counts"><span>Filas procesadas <b>{selected.registrosProcesados}</b></span><span>Identificadas <b>{selected.registrosCorrectos}</b></span><span>No identificadas <b>{selected.asesoresNoIdentificados}</b></span><span>Con error <b>{selected.registrosConError}</b></span></div>{selected.incidencias.length>0&&<details className="time-issues"><summary>Ver incidencias ({selected.incidencias.length})</summary><ul>{selected.incidencias.map((issue,i)=><li key={i}>Fila {issue.fila}: {issue.nombre} — {issue.motivo}</li>)}</ul></details>}{selected.advertencias?.map((warning,i)=><div key={i} className="notice" role="status">{warning}</div>)}<div className="report-date">{displayDate(selected.fechaDatos)}</div><TiemposTable rows={report.registros.slice((reportPage-1)*50,reportPage*50)} onEdit={record=>setModal({type:'edit',record})}/><div className="pagination"><span>{report.registros.length} filas · Incluye asesores activos sin registro · Página {reportPage}</span><div><button className="button secondary" disabled={reportPage===1} onClick={()=>setReportPage(reportPage-1)}>Anterior</button><button className="button secondary" disabled={reportPage*50>=report.registros.length} onClick={()=>setReportPage(reportPage+1)}>Siguiente</button></div></div></>)}
 {tab==='asesor'&&<AsesorHistory version={version} onEdit={record=>setModal({type:'edit',record})}/>}
 </section>{modal?.type==='upload'&&<UploadModal item={modal.item} onClose={()=>setModal(null)} onSaved={item=>{refresh('Archivo procesado y guardado. Revisa las observaciones del reporte.');view(item);}}/>}{modal?.type==='delete'&&<DeleteModal item={modal.item} onClose={()=>setModal(null)} onSaved={()=>{if(reportId===modal.item._id)setReportId(null);refresh('Importación y archivo eliminados. Los acumulados ya están actualizados.');setTab('archivos');}}/>}{modal?.type==='edit'&&<EditModal record={modal.record} onClose={()=>setModal(null)} onSaved={()=>refresh('Corrección guardada. Los acumulados se actualizaron.')}/>}</div>;
}
